FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY packages/shared/package*.json ./packages/shared/

RUN npm ci

COPY . .

WORKDIR /app/apps/api

RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "dev"]
